# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5756bf56e37f93ac64bff35e5024b6b09c92d6fd8cb8f8a6d3412bd1682e01ac2b81776885223613364760ed9a8fa513aea5a8b39016000555c409b412a94f6

test:
  secret_key_base: 5b240b16bf321b9fee7b1dd36d2a5a2107d7ffeeba8c51b81e530af809b10ac22d9fa4cab7a168a58772d9d4f760a39878b60cd5e1ddee778a01892f6127f941

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
